// File generated by FlutterFire CLI / manually configured.
// IMPORTANT: Replace these placeholder values with your real Firebase project config.
// To set up Firebase:
// 1. Go to https://console.firebase.google.com/
// 2. Create a new project named "insurex-app"
// 3. Add an Android/iOS app
// 4. Download google-services.json / GoogleService-Info.plist
// 5. Run: dart pub global activate flutterfire_cli
//         flutterfire configure
// OR manually replace the values below.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static bool get isConfigured {
    try {
      final key = currentPlatform.apiKey;
      return key != 'YOUR_WEB_API_KEY' &&
             key != 'YOUR_ANDROID_API_KEY' &&
             key != 'YOUR_IOS_API_KEY' &&
             !key.startsWith('YOUR_');
    } catch (_) {
      return false;
    }
  }

  // REPLACE THESE WITH YOUR FIREBASE CONFIG
  // ==========================================

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT0ZMDOywfw4Kcvj94mRq0C5wSc3fzzBE',
    appId: '1:194484779958:android:7ce81c5e48e118284b5f17',
    messagingSenderId: '194484779958',
    projectId: 'insuretech-a6674',
    storageBucket: 'insuretech-a6674.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_FwvwutAjsR0hslQvyk2w0VZPY6i8sU',
    appId: '1:194484779958:ios:511d871ecfd103d74b5f17',
    messagingSenderId: '194484779958',
    projectId: 'insuretech-a6674',
    storageBucket: 'insuretech-a6674.firebasestorage.app',
    iosBundleId: 'com.insurex.insurexApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0S1PqJ9INCg7G_LgJmI3eUVlNWVEsQ04',
    appId: '1:194484779958:web:9ace6af12d89f2c34b5f17',
    messagingSenderId: '194484779958',
    projectId: 'insuretech-a6674',
    authDomain: 'insuretech-a6674.firebaseapp.com',
    storageBucket: 'insuretech-a6674.firebasestorage.app',
    measurementId: 'G-52BFX9C62X',
  );
}
